name: docker_scan
description: action for docker scan using anchore/grype
runs:
  using: composite
  steps:
    - name: Build the container image
      shell: bash
      run: docker build . --file src/Dockerfile --tag localbuild/testimage:latest
    - name: Install anchore/grype locally
      shell: bash
      run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
    - name: Run anchore/grype on docker container
      id: scan
      shell: bash
      run: grype -o json --fail-on high localbuild/testimage:latest > ./results.json
    - uses: actions/upload-artifact@v4
      if: ${{ success() || failure() }}
      with:
        name: docker-scan-results
        path: ${{ steps.scan.outputs.json }}
        compression-level: 1
    - name: setup python
      uses: actions/setup-python@v5
      if: ${{ success() || failure() }}
      with:
        python-version: 3.11.8
    - name: pip install
      if: ${{ success() || failure() }}
      shell: bash
      run:  pip install argparse pandas
    - name: Print Results
      if: ${{ success() || failure() }}
      shell: bash
      env:
        path: ${{ steps.scan.outputs.json }}
      run: |
        python ./.github/actions/show_results.py -f $path
