name: Docker Scan
on:
  pull_request:
  push:
    paths:
      - src/Dockerfile
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the container image
        run: docker build . --file src/Dockerfile --tag localbuild/testimage:latest
      - name: run docker scan
        uses: ./.github/actions/docker-scan
      - uses: actions/upload-artifact@v4
        if: ${{ success() || failure() }}
        with:
          name: docker-scan-results
          path: ${{ steps.scan.outputs.json }}
          compression-level: 1
      - name: setup python
        uses: actions/setup-python@v5
        if: ${{ success() || failure() }}
        with:
          python-version: 3.11.8
      - name: pip install
        if: ${{ success() || failure() }}
        run:  pip install argparse pandas
      - name: Print Results
        if: ${{ success() || failure() }}
        env:
          path: ${{ steps.scan.outputs.json }}
        run: |
          python ./.github/actions/show_results.py -f $path
