name: Docker Scan
on:
  pull_request:
  push:
    paths:
      - src/Dockerfile
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run docker scan
        id: scan_action
        uses: ./.github/actions/docker-scan
