name: Container Image CI
on:
  push:
    paths:
      - Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the container image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest
      - uses: anchore/scan-action@v3
        id: scan
        with:
          image: "localbuild/testimage:latest"
          fail-build: false #change to true to fail if security issues found
          severity-cutoff: critical
          output-format: json
          by-cve: true
      - uses: austenstone/json-to-csv@main
        id: csv
        with:
          json: ${{ steps.scan.outputs.json }}
          create-artifact: true
          artifact-name: docker_scan_csv
      - run: echo "${{ steps.csv.outputs.csv }}"
      - run: echo "${{ steps.csv.outputs.artifact-name }}"
