name: Docker Scan
on:
  pull_request:
  workflow_dispatch:
  push:
    paths:
      - src/Dockerfile
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run docker scan
        id: scan_action
        uses: ./.github/actions/docker-scan
