name: Container Image CI
on:
  push:
    paths:
      - Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the container image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest
      - uses: anchore/scan-action@v3
        id: scan
        with:
          image: "localbuild/testimage:latest"
          fail-build: false #change to true to fail if security issues found
          severity-cutoff: critical
          output-format: json
          by-cve: true
      - uses: actions/upload-artifact@v4
        if: ${{ success() || failure() }}
        with:
          name: docker-scan-results
          path: ${{ steps.scan.outputs.json }}
          compression-level: 1
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.8
          run: pip install argparse pandas
      - name: Print Results
        env:
          path: ${{ steps.scan.outputs.json }}
        run: |
          echo $path
          
